name: Run Reminder Job

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, on the hour

jobs:
  run-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Get current UTC hour
        id: time
        run: echo "utc_hour=$(date -u +'%H')" >> $GITHUB_ENV

      - name: Call Reminder API
        run: |
          curl -X GET "https://yourdomain.com/api/reminder-job?hour=${{ env.utc_hour }}"
