name: 'Run Reminder Job'

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:


jobs:
  run-reminder:
    name: Send Reminder to User Emails
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Create .env File
        run: |
          echo "SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        shell: bash

      - name: Get current UTC hour
        id: time
        run: echo "utc_hour=$(date -u +'%H')" >> $GITHUB_ENV

      - name: Call Reminder API
        run: |
          curl -X GET "https://mindgarden.vercel.app/api/cron?hour=${{ env.utc_hour }}"
