name: 'Run Reminder Job'

on:
  push:
    
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour

jobs:
  run-reminder:
      name: Send Reminder to User Emails
      runs-on: ubuntu-latest
      
      strategy:
        fail-fast: false

      steps:
        - name: Get current UTC hour
          id: time
          run: echo "utc_hour=$(date -u +'%H')" >> $GITHUB_ENV

        - name: Call Reminder API
          run: |
            curl -X GET "https://mindgarden.vercel.app/api/cron?hour=${{ env.utc_hour }}"
